apiVersion: apps/v1 
kind: Deployment                                             
metadata:
  name: cache-app                                  
  labels:
    app: cache-app
spec:
  replicas: 1                                                
  selector:
    matchLabels: 
      app: cache-app                               
  template:                                                 
    metadata:
      labels:                                                
        app: cache-app                              
    spec:                                                    
      containers:
      - name: cache-app 
        image: neha16/cache:1.0.3                  
        imagePullPolicy: Always  #IfNotPresent  #Always                         
        ports:
          - name: http
            containerPort: 8080                              
        envFrom:
          - secretRef:
              name: mysql-secret                            
 