apiVersion: v1  
kind: Service                         
metadata:
  name: cache-app             
  labels:                               
    app: cache-app
spec:
  type: NodePort                        
  selector:
    app: cache-app           
  ports: 
  - name: http
    port: 8080
    targetPort: 8080