apiVersion: v1  
kind: Service                           # Type of the kubernetes resource
metadata:
  name: cache-app             # Name of the Kubernetes resource
  labels:                               # Labels that will be applied to the resource
    app: cache-app
spec:
  type: NodePort                        # Gives each node an external IP that’s accessible from outside the cluster and also opens a Port.
  selector:
    app: cache-app            # Selects any Pod with labels `app=cache-app`
  ports: 
  - name: http
    port: 8080
    targetPort: 8080