apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:   
  MYSQL_USER: root
  MYSQL_PASSWORD: "12345678"
  MYSQL_DATABASE: cache-mysql
  MYSQL_ROOT_PASSWORD: "12345678"

  DB_HOST: cache-mysql
  DB_DRIVER: mysql
  DB_USER: root
  DB_PASSWORD: "12345678"
  DB_NAME: cache-mysql
  DB_PORT: "3306"
  
  AMQP_URL: cache-rabbitmq
  AMQP_USERNAME: guest
  AMQP_PASSWORD: guest
  AMQP_PORT: "5672"