apiVersion: v1
kind: PersistentVolumeClaim             
metadata:                              
  name: mysql-pv-claim
  labels:
    app: cache-mysql
spec:                                
  storageClassName: manual              
  accessModes:
    - ReadWriteMany                  
  resources:
    requests:
      storage: 5Gi