apiVersion: v1
kind: PersistentVolume                     
metadata:
  name: mysql-pv-volume
  labels:
    type: local
    app: cache-mysql
spec:
  storageClassName: manual                 
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:                                
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain 