apiVersion: v1                           
kind: Service                           
metadata:
  name: cache-mysql                
  labels:                               
    app: cache-mysql
spec:
  type: NodePort
  ports:
    - port: 3306
  selector:                             
    app: cache-mysql
    tier: mysql 